version: 2.1

jobs:
  build_and_deploy:
    docker:
      - image: cimg/node:current
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          name: Save cache
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run:
          name: Inject configuration into environments.ts
          command: |
            mkdir -p src/environments
            echo -e "const STEAM_API_KEY = '${API_KEY}'; \n const POSTGRES_POOL = {user: '${PG_USER}', host: '${PG_HOST}', database: '${PG_DB}', password: '${PG_PASS}', port: '${PG_PORT}'};  \n module.exports = {STEAM_API_KEY, POSTGRES_POOL};" > src/environments/environment.js
      - run:
          name: Compile into one file
          command: |
            sudo npm i -g @vercel/ncc
            ncc build src/game-stats.js -o dist
      - run:
          name: Set up deployment
          command: |
            sudo apt-get update
            sudo apt-get install sshpass
            ssh-keyscan ${IP} >> /home/circleci/.ssh/known_hosts
      - run:
          name: Deploy to server
          command: |
            sshpass -p ${PASS} scp dist/index.js $VPS:/root/scripts/deployments/game-stats/${CIRCLE_BUILD_NUM}.js

workflows:
  build_and_deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: main
