version: 2.1

jobs:
  build_and_deploy:
    docker:
      - image: cimg/node:current
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Inject configuration into environments.ts
          command: |
            mkdir -p src/environments
            touch src/environments/environments.js
            echo -e "const STEAM_API_KEY = "${API_KEY}"; \n module.exports = { \n STEAM_API_KEY \n };" > src/environments/environment.js
      - run:
          name: Compile into one file
          command: |
            sudo npm i -g @vercel/ncc
            ncc build src/game-stats.js -o dist
      - run:
          name: Deploy to server
          command: |
            scp -r -P ${PASS} dist/index.js ${VPS}:/root/scripts/deployments/${CIRCLE_BUILD_NUM}
          


workflows:
  build_and_deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: main
